apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flaresolverr
  policy:
    semver:
      range: ">=0.0.0"
