apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zigbee2mqtt
  policy:
    semver:
      range: ">=0.0.0"
