apiVersion: v1
kind: Secret
metadata:
    name: telegram-webhook
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oObJDE1DM+rJ0VKymTDIrxta7LmAoPVDwZ6+KDXdtS26PQRbTiVKI0i4FAgTWg==,iv:tl9Tt9Q8lNNvqYNmqgdxIEi0kCsOSPnynT1gVrb9pE8=,tag:L6LdmB87pv9fYk2L6XB75g==,type:str]
sops:
    age:
        - recipient: age1tchhe2qzlqtha74w7r8txrynr3xlpzrfwepql57jw7z4autpyqcs7uj226
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM254dzJkdExPVk43UmRR
            clFKRWhabWpITTFvK3VjT3h4aHh4WDhzemlNCnVRZXRMNExSbElTSnNRQnBWUGsz
            L1ZqQlhnckJSMnExWElOalFXM3J1dUkKLS0tIGZKSHJEUG45VEl0RUFSdUlNMFoz
            SW5zSTVXNDhLRnlNM0txVVN3ZGhPVUEKGAIxu7yElLEfa5FEAhz84HC2GCSZr4TC
            /4eqOTdd5vVxKRxbuD804FWGpdMheWhDNOO90a72dN0JADYkAp5pZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T00:33:57Z"
    mac: ENC[AES256_GCM,data:jCo0pUV4pFayKjDOYeGonA6QMPLN4H7xJjRJa7xJ4ZTrs9LKM77UdummxvJIAy1fWbprAQG3Z4To0ZkCCX5nX82wWk5xzDq1g3/k7TLktx6pK0gp9l0AqhnfVK46ApWZKVst46+a7/+VgYKJuHeX/MXI151ZLh0HuA9kj6yZ/uE=,iv:9QpI6N8XDzNXdDQUUNUfqmwAf50d1oN2mt7obQrbfAc=,tag:20jE6T8MIBqjdkbIw7qDHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
