---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: prometheus-blackbox-exporter
  namespace: platform-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: prometheus-blackbox-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
