---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-grafana-credentials
  namespace: platform-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: external-secrets-store
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana_admin_user
    - secretKey: admin-password
      remoteRef:
        key: grafana_admin_password
