---
fullnameOverride: argocd

configs:
  secret:
    createSecret: true
  params:
    server.insecure: "true"
    controller.diff.server.side: "true"
  cm:
    resource.ignoreResourceUpdatesEnabled: "true"
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        - .webhooks[].failurePolicy
        - .metadata.generation

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true
  deploymentAnnotations:
    reloader.stakater.com/auto: "true"

controller:
  statefulsetAnnotations:
    reloader.stakater.com/auto: "true"
  metrics:
    enabled: true

server:
  deploymentAnnotations:
    reloader.stakater.com/auto: "true"
  httproute:
    enabled: true
    parentRefs:
      - name: gateway
        namespace: platform-system
        sectionName: https
    hostnames:
      - argocd.edgard.org
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

repoServer:
  deploymentAnnotations:
    reloader.stakater.com/auto: "true"
