---
defaultPodOptions:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0

controllers:
  main:
    type: deployment
    replicas: 1
    strategy: Recreate
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      hostNetwork: true
    containers:
      app:
        image:
          repository: openthread/border-router
          tag: sha-9909ab3
        env:
          OT_INFRA_IF: br0
          OT_LOG_LEVEL: "7"
          OT_RCP_DEVICE: spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800
          OT_REST_LISTEN_ADDR: 0.0.0.0
          OT_REST_LISTEN_PORT: "8081"
          OT_THREAD_IF: wpan0
        ports:
          - name: rest
            containerPort: 8081
            protocol: TCP
        probes:
          startup:
            enabled: true
          liveness:
            enabled: true
          readiness:
            enabled: true
        securityContext:
          privileged: true

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      rest:
        enabled: true
        port: 8081
        protocol: TCP
        targetPort: 8081

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /data
  dev-ttyusb0:
    type: hostPath
    hostPath: /dev/ttyUSB0
    hostPathType: CharDevice
  dev-tun:
    type: hostPath
    hostPath: /dev/net/tun
    hostPathType: CharDevice
