---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matterbridge-config
  namespace: home-automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: matterbridge-config
    creationPolicy: Owner
  data:
    - secretKey: matterbridge-hass.config.json
      remoteRef:
        key: cluster-secrets
        property: matterbridge_hass_config
