apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: Recreate
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/sonarr
              tag: 4.0.15 # {"$imagepolicy": "flux-system:sonarr:tag"}
            env:
              TZ: Europe/Warsaw
              PUID: "568"
              PGID: "568"
              UMASK: "022"
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8989
                  failureThreshold: 30
                  periodSeconds: 10
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8989
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8989
                  initialDelaySeconds: 15
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 384Mi
              limits:
                memory: 768Mi
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 8989
            targetPort: 8989
    persistence:
      config:
        type: hostPath
        hostPath: /mnt/spool/appdata/sonarr
        globalMounts:
          - path: /config
      media:
        type: hostPath
        hostPath: /mnt/dpool/media
        globalMounts:
          - path: /media
