---
defaultPodOptions:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0

controllers:
  main:
    strategy: Recreate
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-lan-bridge",
            "namespace": "kube-system",
            "ips": ["192.168.1.244/24"],
            "gateway": ["192.168.1.1"],
            "mac": "02:42:c0:a8:01:f4"
          }]
    initContainers:
      init:
        image:
          repository: restic/rest-server
          tag: 0.14.0
        command:
          - /bin/sh
          - -c
          - |
            if [ ! -f /repository/.htpasswd ]; then
              echo "Creating htpasswd file..."
              htpasswd -Bbc /repository/.htpasswd restic "$RESTIC_PASSWORD"
            fi
        env:
          RESTIC_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: restic-credentials
                key: RESTIC_PASSWORD
        securityContext:
          allowPrivilegeEscalation: false
    containers:
      app:
        image:
          repository: restic/rest-server
          tag: 0.14.0
        securityContext:
          allowPrivilegeEscalation: false
        command:
          - rest-server
        args:
          - --path=/repository
          - --htpasswd-file=/repository/.htpasswd
        probes:
          startup:
            enabled: true
          liveness:
            enabled: true
          readiness:
            enabled: true

service:
  main:
    controller: main
    ports:
      http:
        port: 8000
        protocol: TCP

persistence:
  repo:
    type: persistentVolumeClaim
    existingClaim: restic-repo
    globalMounts:
      - path: /repository
