---
- name: Destroy platform and reset Talos node
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy platform
      ansible.builtin.include_role:
        name: platform
        tasks_from: destroy

    - name: Reset Talos node
      ansible.builtin.include_role:
        name: talos
        tasks_from: reset
