---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victoria-metrics-k8s-stack-grafana-alerting-credentials
  namespace: platform-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: external-secrets-store
    kind: ClusterSecretStore
  target:
    name: grafana-alerting-credentials
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: telegram_bot_token
    - secretKey: TELEGRAM_CHAT_ID
      remoteRef:
        key: telegram_chat_id
