---
defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

controllers:
  main:
    type: deployment
    replicas: 1
    strategy: Recreate
    containers:
      app:
        image:
          repository: ghcr.io/atuinsh/atuin
          tag: 18.15.2
        args:
          - start
        env:
          ATUIN_DB_URI: sqlite:///config/atuin.db
          ATUIN_HOST: 0.0.0.0
          ATUIN_PORT: "8888"
          ATUIN_OPEN_REGISTRATION: "false"
        ports:
          - name: http
            containerPort: 8888
        probes:
          startup:
            enabled: true
          liveness:
            enabled: true
          readiness:
            enabled: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          limits: null
          requests: null

service:
  main:
    controller: main
    primary: true
    forceRename: atuin
    annotations:
      gatus.edgard.org/enabled: "true"
    ports:
      http:
        port: 8888

route:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Atuin
      gethomepage.dev/group: Selfhosted
      gethomepage.dev/icon: atuin.svg
      gethomepage.dev/app: atuin
    parentRefs:
      - name: gateway
        namespace: platform-system
        sectionName: https
    hostnames:
      - atuin.edgard.org
    rules:
      - backendRefs:
          - identifier: main
            port: 8888

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    advancedMounts:
      main:
        app:
          - path: /config
