---
defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    type: deployment
    replicas: 1
    strategy: Recreate
    containers:
      app:
        image:
          repository: ghcr.io/cenodude/crosswatch
          tag: 0.12.4
        env:
          TZ: Europe/Warsaw
        ports:
          - name: http
            containerPort: 8787
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: http
              periodSeconds: 10
              failureThreshold: 30
              timeoutSeconds: 5
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: http
              periodSeconds: 30
              timeoutSeconds: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: http
              periodSeconds: 10
              timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 8787
        targetPort: http

route:
  main:
    parentRefs:
      - name: gateway
        namespace: platform-system
        sectionName: https
    hostnames:
      - crosswatch.edgard.org
    rules:
      - backendRefs:
          - identifier: main
            port: 8787

persistence:
  config:
    type: persistentVolumeClaim
    forceRename: crosswatch-config
    accessMode: ReadWriteOnce
    size: 5Gi
    annotations:
      argocd.argoproj.io/sync-options: Delete=false
    globalMounts:
      - path: /config
