---
talos_config_dir: "{{ home_dir }}/.talos"
talos_config_path: "{{ talos_config_dir }}/config"
talos_controlplane_config_path: "{{ talos_config_dir }}/controlplane.yaml"
talos_controlplane_patch_file: "{{ role_path }}/files/controlplane-patch.yaml"
talos_secrets_file: "{{ role_path }}/files/secrets.vault.yml"
talos_api_wait_retries: 30
talos_api_wait_delay: 5
talos_health_wait_timeout: 5m
talos_upgrade_test_mode: false
