---
talos_upgrade:
  installer:
    repository: ghcr.io/siderolabs/installer
    # renovate: datasource=github-releases depName=siderolabs/talos
    version: v1.13.5
  upgrade:
    rebootMode: default
    timeout: 30m
