---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-blackbox-targets
  namespace: ops
data:
  http.yaml: |
    - labels: {group: gateway, scope: external, name: id-external}
      targets: [https://id.edgard.org/]
    - labels: {group: edge-services, scope: internal, name: changedetection}
      targets: [http://changedetection.edge-services.svc.cluster.local:5000/]
    - labels: {group: edge-services, scope: internal, name: echo}
      targets: [http://echo.edge-services.svc.cluster.local:80/]
    - labels: {group: edge-services, scope: internal, name: hajimari}
      targets: [http://hajimari.edge-services.svc.cluster.local:3000/]
    - labels: {group: edge-services, scope: internal, name: manyfold}
      targets: [http://manyfold.edge-services.svc.cluster.local:3214/health]
    - labels: {group: edge-services, scope: internal, name: paperless-ai}
      targets: [http://paperless-ai.edge-services.svc.cluster.local:3000/]
    - labels: {group: home-automation, scope: internal, name: home-assistant}
      targets: [http://home-assistant.home-automation.svc.cluster.local:8123/]
    - labels: {group: home-automation, scope: internal, name: zigbee2mqtt}
      targets: [http://zigbee2mqtt.home-automation.svc.cluster.local:8080/]
    - labels: {group: media, scope: internal, name: bazarr}
      targets: [http://bazarr.media.svc.cluster.local:6767/]
    - labels: {group: media, scope: internal, name: flaresolverr}
      targets: [http://flaresolverr.media.svc.cluster.local:8191/health]
    - labels: {group: media, scope: internal, name: jellyfin}
      targets: [http://jellyfin.media.svc.cluster.local:8096/health]
    - labels: {group: media, scope: internal, name: prowlarr}
      targets: [http://prowlarr.media.svc.cluster.local:9696/]
    - labels: {group: media, scope: internal, name: qbittorrent}
      targets: [http://qbittorrent.media.svc.cluster.local:8080/]
    - labels: {group: media, scope: internal, name: radarr}
      targets: [http://radarr.media.svc.cluster.local:7878/]
    - labels: {group: media, scope: internal, name: sonarr}
      targets: [http://sonarr.media.svc.cluster.local:8989/]
    - labels: {group: ops, scope: internal, name: kopia}
      targets: [http://kopia.ops.svc.cluster.local:51515/]
    - labels: {group: platform-system, scope: internal, name: cloudflared}
      targets: [http://cloudflared.platform-system.svc.cluster.local:8080/ready]
  tcp.yaml: |
    - labels: {group: gateway, scope: internal, name: envoy-gateway-external}
      targets: [envoy-gateway-external.platform-system.svc.cluster.local:443]
    - labels: {group: gateway, scope: internal, name: envoy-gateway-internal}
      targets: [envoy-gateway-internal.platform-system.svc.cluster.local:443]
    - labels: {group: edge-services, scope: internal, name: atuin}
      targets: [atuin.edge-services.svc.cluster.local:8888]
    - labels: {group: edge-services, scope: internal, name: karakeep}
      targets: [karakeep.edge-services.svc.cluster.local:3000]
    - labels: {group: edge-services, scope: internal, name: nginx}
      targets: [nginx.edge-services.svc.cluster.local:80]
    - labels: {group: edge-services, scope: internal, name: paperless}
      targets: [paperless.edge-services.svc.cluster.local:8000]
    - labels: {group: home-automation, scope: internal, name: mosquitto}
      targets: [mosquitto.home-automation.svc.cluster.local:1883]
    - labels: {group: platform-system, scope: internal, name: dex}
      targets: [dex.platform-system.svc.cluster.local:5556]
  icmp.yaml: |-
    - labels: {group: connectivity, scope: external, name: ping-google}
      targets: [www.google.com]
    - labels: {group: connectivity, scope: external, name: ping-microsoft}
      targets: [www.microsoft.com]
    - labels: {group: connectivity, scope: external, name: ping-amazon}
      targets: [www.amazon.com]
