---
name: CI

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Task
        uses: go-task/setup-task@v1

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false

      - name: Set up yq
        uses: dcarbone/install-yq-action@v1
        with:
          version: v4.44.6

      - name: Set up pluto
        uses: FairwindsOps/pluto/github-action@v5.23.5

      - name: Set up kubeconform
        uses: bmuschko/setup-kubeconform@v1
        with:
          kubeconform-version: "0.7.0"

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats shellcheck yamllint

      - name: Run quality gate
        run: task lint
