---
name: CI

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Task
        uses: go-task/setup-task@3be4020d41929789a01026e0e427a4321ce0ad44 # v2.0.0
        with:
          # renovate: datasource=github-releases depName=go-task/task
          version: 3.50.0

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          # renovate: datasource=github-releases depName=helm/helm
          version: v4.1.4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
        with:
          # renovate: datasource=github-releases depName=opentofu/opentofu
          tofu_version: 1.11.6
          tofu_wrapper: false

      - name: Set up yq
        uses: dcarbone/install-yq-action@4075b4dca348d74bd83f2bf82d30f25d7c54539b # v1.3.1
        with:
          # renovate: datasource=github-tags depName=mikefarah/yq
          version: v4.53.2

      - name: Set up pluto
        uses: FairwindsOps/pluto/github-action@dd5ec8cccce5e42dfe8054b8250baa35546056a0 # v5.24.0
        with:
          # renovate: datasource=docker depName=us-docker.pkg.dev/fairwinds-ops/oss/pluto
          IMAGE_TAG: v5.23

      - name: Set up kubeconform
        uses: bmuschko/setup-kubeconform@5ccaecbbf012bcb1eeeab66e649db64a477ade8f # v1.0.0
        with:
          # renovate: datasource=github-releases depName=yannh/kubeconform
          kubeconform-version: "0.7.0"

      - name: Set up Conftest
        uses: princespaghetti/setup-conftest@417586a9b2e806fc5a95c72dfe98e296ef092b6f # v1.2.0
        with:
          # renovate: datasource=github-releases depName=open-policy-agent/conftest
          version: 0.68.2

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint

      - name: Run quality gate
        run: task lint
