---
global:
  istioNamespace: platform-system
  configRootNamespace: platform-system
  proxy:
    autoInject: disabled

env:
  METRICS_LOCALHOST_ACCESS_ONLY: "true"

meshConfig:
  defaultConfig:
    proxyMetadata:
      METRICS_LOCALHOST_ACCESS_ONLY: "true"
  defaultProviders:
    metrics: []
  enablePrometheusMerge: false

sidecarInjectorWebhook:
  enabled: false

base:
  validationFailurePolicy: Fail

pilot:
  autoscaleEnabled: false

resources:
  limits: null
  requests: null
