---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8up-restic-credentials
  namespace: selfhosted
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: external-secrets-store
    kind: ClusterSecretStore
  target:
    name: k8up-restic-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_USERNAME: restic
        RESTIC_PASSWORD: "{{ .restic_password }}"
  data:
    - secretKey: restic_password
      remoteRef:
        key: restic_server_password
